config/routes.rb
# NOTE: helper classes for org constraints
class OrganizationPresent
  def current_user(request)
    User.find_by(id: request.session[:user_id])
  end

  def self.matches?(_request)
    Current.organization.present?
  end
end

# NOTE: helper classes for org constraints
class OrganizationNotPresent
  def current_user(request)
    User.find_by(id: request.session[:user_id])
  end

  def self.matches?(_request)
    Current.organization.nil?
  end
end

# Routes
Rails.application.routes.draw do
  root 'pages#home', constraints: OrganizationNotPresent
  root 'dashboard/index#index', constraints: OrganizationPresent

  namespace :users do
    resources :signups, only: %i[index new create]
    resources :sessions, only: %i[index new create]
  end
  get 'signup' => 'users/signups#new', as: :signup
  get 'login' => 'users/sessions#new', as: :login
  post 'logout' => 'users/sessions#destroy', as: :logout

  scope module: :dashboard do
    get '/:organization_id' => 'index#index', as: :organization_root
    resources :organizations
    resources :projects, param: :project_id
  end

  namespace :account do
    resource :settings, only: %i[update] do
      collection { get '/', action: :edit }
    end
    resource :notifications, only: %i[update] do
      collection { get '/', action: :edit }
    end
  end
end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  layout 'dashboard'

  before_action :require_project

  private

  def require_project
    redirect_to :new_project if Current.user.projects.empty?
  end

end

app/controllers/dashboard/index_controller.rb
class Dashboard::IndexController < Dashboard::BaseController
  def index
    @projects = ProjectDecorator.decorate_collection(Current.user.projects)
  end
end

app/controllers/dashboard/organizations_controller.rb
class Dashboard::OrganizationsController < Dashboard::BaseController
  def index; end

  def new
    @onboarding = true
    @org_form = Onboard::OrganizationForm.new
  end

  def create
    @org_form = Onboard::OrganizationForm.from_params(params)
    Onboard::CreateOrganization.call(@org_form) do
      on(:ok) do
        flash[:notice] = 'Successfully created organization'
        redirect_back_or_to organization_home
      end
      on(:invalid) { render :new }
    end
  end
end

app/controllers/dashboard/projects_controller.rb
class Dashboard::ProjectsController < Dashboard::BaseController
  before_action :set_project, only: %i[show edit update]
  before_action :set_current_supported_languages, only: %i[new edit create update]
  before_action :set_presenter, only: %i[new edit create update]

  skip_before_action :require_project

  def new
    redirect_to :new_organization if Current.user.organizations.empty?
    @project_form = Onboard::ProjectForm.new
    @onboarding = true
  end

  def create
    @project_form = Onboard::ProjectForm.from_params(params)
    Onboard::CreateProject.call(@project_form) do
      on(:ok) do
        flash[:notice] = 'Successfully created project'
        redirect_back_or_to organization_home
      end
      on(:invalid) { render :new }
    end
  end

  def show; end

  def edit; end

  def update; end

  private

  def set_project
    @project = Project.friendly.find(params[:project_id])
  end

  def set_presenter
    present Onboard::ProjectPresenter.new(user: Current.user)
  end

  def set_supported_languages
    @supported_languages = SupportedLanguage.active
  end
end

app/views/dashboard/shared/_footer.html.slim
footer.footer
  .container-fluid
    .row
      .col-12
        .pull-right.hide-phone
          |  Build
          strong.text-custom
            |  1.0.0
          | .
        div
          strong
            |  Relay
          |  - Copyright © 2017 - 2018

app/views/dashboard/shared/_nav.html.slim
header#topnav
  .topbar-main
    .container-fluid
      .logo
        = link_to root_path do
          .logo__img
            = image_tag asset_pack_path('images/logo-light.png'), height: '26', class: 'logo-large'
          .logo__text Relay
      - unless @onboarding
        .navbar-custom
          #navigation
            ul.navigation-menu
              li.has-submenu
                = link_to root_path do
                  span
                    i.ti-home
              li.has-submenu
                a[href="#"]

                  span = @project.present? ? @project.name : 'Projects'
                  i.mdi.mdi-chevron-down
                ul.submenu
                  - if current_user.projects.size > 0
                    - current_user.projects.each do |p|
                      li = link_to p.name, project_path(p.slug)
                  - else
                    li
                      a No projects
                  li.divider
                  li
                    = link_to :new_project do
                      |  Create Project
              li.has-submenu
                a[href="#"]
                  span
                    | Statistics
              li.has-submenu
                a[href="#"]
                  span
                    | Team
              li.has-submenu
                a[href="#"]
                  span
                    | Settings
      .menu-extras.topbar-custom
        ul.list-unstyled.topbar-right-menu.float-right.mb-0
          li.menu-item
            a.navbar-toggle.nav-link
            .lines
              span
              span
              span
          - unless @onboarding
            li.dropdown.hide-phone
              a.nav-link.dropdown-toggle.waves-effect.waves-light.nav-user[data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false"]
                = Current.organization.name.titleize
                i.mdi.mdi-chevron-down
                .dropdown-menu.dropdown-menu-right
                  - if Current.organizations.size > 0
                    - Current.organizations.each do |org|
                        = link_to org.name.titleize, organization_home(org),
                          class: 'dropdown-item'
                  = link_to :new_organization,
                    class: 'dropdown-item' do
                     | Create Organization
          li.dropdown
            a.nav-link.dropdown-toggle.waves-effect.waves-light.nav-user[data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false"]
              = image_tag url_for(Current.user.avatar), class: 'rounded-circle'
                i.mdi.mdi-chevron-down
            .dropdown-menu.dropdown-menu-right.profile-dropdown
              .dropdown-item.noti-title
                h6.text-overflow.m-0 = Current.user.name
              = link_to account_settings_path(script_name: false), class: 'dropdown-item notify-item' do
                i.ti-settings
                span Account Settings
              a.dropdown-item.notify-item[href="javascript:void(0);"]
                i.ti-lock
                span
                  | Lock Screen
              = link_to logout_path(script_name: false), method: :post, class: 'dropdown-item notify-item' do
                i.ti-power-off
                span
                  | Logout
      .clearfix